name: cicd-prototype.yml

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "stage"
        required: true
        type: choice
        options:
          - stage
          - prod

# If more than one workflow for the same ref are triggered, cancel the oldest
# head_ref is the branch the pull_request was made from, otherwise it's branch the workflow is trigger on (for push)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build-clutchtech-internal-ui:
    environment: ${{ github.event.inputs.environment == 'prod' && github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - run: ls -lah
      
      - run: | 
          echo ${{ github.event.inputs.environment }}
          echo ${{ secrets.TEST_SECRET == 'proding' && 'it is a prod' || 'it is not prod' }}
           