name: cicd-prototype.yml

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, master, main]

# If more than one workflow for the same ref are triggered, cancel the oldest
# head_ref is the branch the pull_request was made from, otherwise it's branch the workflow is trigger on (for push)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  app-name: "test-ui"
  aws-region: "us-east-1"
  arty_npmrc_registry: "https://artifactory.coxautoinc.com/clutch-npm/"
  test: true

jobs:
  test-ui:
    runs-on: CAI-Enterprise-Ubuntu-Latest
    steps:
      - uses: actions/checkout@v3

      - id: set-creds
        name: set artifactory credentials
        run: |
          TEXT_TO_COPY="@clutch:registry=${{ env.arty_npmrc_registry }} \n
          //artifactory.coxautoinc.com/clutch-npm/:_authToken=${{ secrets.ARTY_NPMRC_TOKEN }} \n
          //artifactory.coxautoinc.com/clutch-npm-local/:_authToken=${{ secrets.ARTY_NPMRC_TOKEN }} \n
          email=${{ secrets.ARTY_NPRMC_EMAIL }} \n
          always-auth=true \n"
          echo "TEXT_TO_COPY<<EOF" > ~/.npmrc
