name: cicd-prototype.yml

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, master, main]

# If more than one workflow for the same ref are triggered, cancel the oldest
# head_ref is the branch the pull_request was made from, otherwise it's branch the workflow is trigger on (for push)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build-clutchtech-internal-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tester
    steps:
      - uses: actions/checkout@v3
            
      - run: ls -lah

      - id: archive-params
        run: echo "::set-output name=name::${{ github.sha }}-${{ github.run_number }}.tar.xz"

      - id: archive
        run: tar cf - build | xz -4e > "${{ steps.archive-params.outputs.name }}"

      - run: ls -lah

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive-params.outputs.name }}
          path: ${{ steps.archive-params.outputs.name }}
          if-no-files-found: error
          retention-days: 1